import { createRequestHandler } from "@remix-run/netlify";
import * as build from "@remix-run/dev/server-build";

/*
 * Returns a context object with at most 3 keys:
 *  - `netlifyGraphToken`: raw authentication token to use with Netlify Graph
 *  - `clientNetlifyGraphAccessToken`: For use with JWTs generated by
 *    `netlify-graph-auth`.
 *  - `netlifyGraphSignature`: a signature for subscription events. Will be
 *    present if a secret is set.
 */
function getLoadContext(event, context) {
    let rawAuthorizationString;
    let netlifyGraphToken;

    if (event.authlifyToken != null) {
        netlifyGraphToken = event.authlifyToken;
    }

    // eslint-disable-next-line
    let authHeader = event.headers["authorization"];
    let graphSignatureHeader = event.headers["x-netlify-graph-signature"];

    if (authHeader != null && /Bearer /gi.test(authHeader)) {
        rawAuthorizationString = authHeader.split(" ")[1];
    }

    let loadContext = {
        clientNetlifyGraphAccessToken: rawAuthorizationString,
        netlifyGraphToken: netlifyGraphToken,
        netlifyGraphSignature: graphSignatureHeader
    };

    // Remove keys with undefined values
    Object.keys(loadContext).forEach((key) => {
        if (loadContext[key] == null) {
            delete loadContext[key];
        }
    });

    return loadContext;
}

export const handler = createRequestHandler({
    build,
    getLoadContext,
    mode: process.env.NODE_ENV
});

/*
const path = require("path");
const express = require("express");
const compression = require("compression");
const morgan = require("morgan");
const { createRequestHandler } = require("@remix-run/express");

const BUILD_DIR = path.join(process.cwd(), "build");

const app = express();

app.use(
    compression({
        filter: (req) => req.headers["Content-Type"]?.startsWith("text/event-stream")
    })
);

// http://expressjs.com/en/advanced/best-practice-security.html#at-a-minimum-disable-x-powered-by-header
app.disable("x-powered-by");

// Remix fingerprints its assets so we can cache forever.
app.use("/build", express.static("public/build", { immutable: true, maxAge: "1y" }));

// Everything else (like favicon.ico) is cached for an hour. You may want to be
// more aggressive with this caching.
app.use(express.static("public", { maxAge: "1h" }));

app.use(morgan("tiny"));

app.all(
    "*",
    process.env.NODE_ENV === "development"
        ? (req, res, next) => {
              purgeRequireCache();

              return createRequestHandler({
                  build: require(BUILD_DIR),
                  mode: process.env.NODE_ENV
              })(req, res, next);
          }
        : createRequestHandler({
              build: require(BUILD_DIR),
              mode: process.env.NODE_ENV
          })
);
const port = process.env.PORT || 6112;

app.listen(port, () => {
    console.log(`Express server listening on port ${port}`);
});

function purgeRequireCache() {
    // purge require cache on requests for "server side HMR" this won't let
    // you have in-memory objects between requests in development,
    // alternatively you can set up nodemon/pm2-dev to restart the server on
    // file changes, but then you'll have to reconnect to databases/etc on each
    // change. We prefer the DX of this, so we've included it for you by default
    for (let key in require.cache) {
        if (key.startsWith(BUILD_DIR)) {
            delete require.cache[key];
        }
    }
}
 */
